apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi
          image: python:3.11-slim
          command: ["sh", "-c"]
          args:
            - |
              pip install fastapi uvicorn pydantic &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
          workingDir: /app
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          configMap:
            name: fastapi-app-code
